// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyDoanKham.API.Data;

#nullable disable

namespace QuanLyDoanKham.API.Migrations.Spec
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427105547_InitialSpecSchemaWithSeedData")]
    partial class InitialSpecSchemaWithSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<decimal>("WorkUnits")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("StaffId", "TeamId");

                    b.ToTable("Spec_AttendanceRecords", (string)null);
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContractCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("ContractCode")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Spec_Contracts", (string)null);
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Spec_Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "HCNS",
                            Name = "Hành chính Nhân sự"
                        },
                        new
                        {
                            Id = 2,
                            Code = "KHO",
                            Name = "Kho"
                        },
                        new
                        {
                            Id = 3,
                            Code = "KETOAN",
                            Name = "Kế toán"
                        });
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.ExamPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "Code")
                        .IsUnique();

                    b.ToTable("Spec_ExamPositions", (string)null);
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.ExaminationTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ExamDate")
                        .HasColumnType("date");

                    b.Property<int?>("LeaderStaffId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TeamCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ExamDate");

                    b.HasIndex("LeaderStaffId");

                    b.HasIndex("TeamCode")
                        .IsUnique();

                    b.ToTable("Spec_ExaminationTeams", (string)null);
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.InventoryIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("ItemId", "TeamId");

                    b.ToTable("Spec_InventoryIssues", (string)null);
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MinThreshold")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Spec_InventoryItems", (string)null);
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.InventoryReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateOnly>("ReceiptDate")
                        .HasColumnType("date");

                    b.Property<string>("Supplier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Spec_InventoryReceipts", (string)null);
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.OtherExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Spec_OtherExpenses", (string)null);
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.PatientExamRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamPositionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamPositionId");

                    b.HasIndex("PatientId", "ExamPositionId")
                        .IsUnique();

                    b.ToTable("Spec_PatientExamRecords", (string)null);
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.QRSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("QRCode")
                        .IsUnique();

                    b.HasIndex("TeamId", "IsActive");

                    b.ToTable("Spec_QRSessions", (string)null);
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Spec_Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "HCNS",
                            Name = "HCNS"
                        },
                        new
                        {
                            Id = 2,
                            Code = "KHO",
                            Name = "Kho"
                        },
                        new
                        {
                            Id = 3,
                            Code = "MANAGER",
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 4,
                            Code = "TRUONGDOAN",
                            Name = "Trưởng Đoàn"
                        },
                        new
                        {
                            Id = 5,
                            Code = "KETOAN",
                            Name = "Kế toán"
                        },
                        new
                        {
                            Id = 6,
                            Code = "ADMIN",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("Spec_RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 16
                        });
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.SpecPatient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("WorkUnit")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TeamId");

                    b.ToTable("Spec_Patients", (string)null);
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.SpecPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Feature", "Action")
                        .IsUnique();

                    b.ToTable("Spec_Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "View",
                            Feature = "Contract"
                        },
                        new
                        {
                            Id = 2,
                            Action = "Create",
                            Feature = "Contract"
                        },
                        new
                        {
                            Id = 3,
                            Action = "Edit",
                            Feature = "Contract"
                        },
                        new
                        {
                            Id = 4,
                            Action = "Approve",
                            Feature = "Contract"
                        },
                        new
                        {
                            Id = 5,
                            Action = "View",
                            Feature = "Team"
                        },
                        new
                        {
                            Id = 6,
                            Action = "Create",
                            Feature = "Team"
                        },
                        new
                        {
                            Id = 7,
                            Action = "Edit",
                            Feature = "Team"
                        },
                        new
                        {
                            Id = 8,
                            Action = "AssignStaff",
                            Feature = "Team"
                        },
                        new
                        {
                            Id = 9,
                            Action = "Generate",
                            Feature = "QR"
                        },
                        new
                        {
                            Id = 10,
                            Action = "View",
                            Feature = "Attendance"
                        },
                        new
                        {
                            Id = 11,
                            Action = "View",
                            Feature = "Inventory"
                        },
                        new
                        {
                            Id = 12,
                            Action = "Create",
                            Feature = "Inventory"
                        },
                        new
                        {
                            Id = 13,
                            Action = "View",
                            Feature = "Finance"
                        },
                        new
                        {
                            Id = 14,
                            Action = "View",
                            Feature = "Report"
                        },
                        new
                        {
                            Id = 15,
                            Action = "Manage",
                            Feature = "Staff"
                        },
                        new
                        {
                            Id = 16,
                            Action = "Manage",
                            Feature = "Permission"
                        });
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.SpecStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ProfessionalRole")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Spec_Staffs", (string)null);
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.TeamFinance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MaterialCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StaffCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("Spec_TeamFinances", (string)null);
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.TeamStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamPositionId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamPositionId");

                    b.HasIndex("StaffId");

                    b.HasIndex("TeamId", "StaffId", "ExamPositionId");

                    b.ToTable("Spec_TeamStaffs", (string)null);
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Spec_Users", (string)null);
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("Spec_UserRoles", (string)null);
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.AttendanceRecord", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Spec.SpecStaff", "Staff")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.Spec.ExaminationTeam", "Team")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.Contract", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Spec.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuanLyDoanKham.API.Models.Spec.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ApprovedByUser");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.ExamPosition", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Spec.ExaminationTeam", "Team")
                        .WithMany("ExamPositions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.ExaminationTeam", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Spec.Contract", "Contract")
                        .WithMany("ExaminationTeams")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.Spec.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuanLyDoanKham.API.Models.Spec.SpecStaff", "LeaderStaff")
                        .WithMany()
                        .HasForeignKey("LeaderStaffId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Contract");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LeaderStaff");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.InventoryIssue", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Spec.InventoryItem", "Item")
                        .WithMany("Issues")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.Spec.ExaminationTeam", "Team")
                        .WithMany("InventoryIssues")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.InventoryReceipt", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Spec.InventoryItem", "Item")
                        .WithMany("Receipts")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.OtherExpense", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Spec.ExaminationTeam", "Team")
                        .WithMany("OtherExpenses")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.PatientExamRecord", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Spec.ExamPosition", "ExamPosition")
                        .WithMany("PatientExamRecords")
                        .HasForeignKey("ExamPositionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.Spec.SpecPatient", "Patient")
                        .WithMany("ExamRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamPosition");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.QRSession", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Spec.ExaminationTeam", "Team")
                        .WithMany("QRSessions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.RolePermission", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Spec.SpecPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.Spec.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.SpecPatient", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Spec.ExaminationTeam", "Team")
                        .WithMany("Patients")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.SpecStaff", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Spec.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyDoanKham.API.Models.Spec.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.TeamFinance", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Spec.ExaminationTeam", "Team")
                        .WithOne("TeamFinance")
                        .HasForeignKey("QuanLyDoanKham.API.Models.Spec.TeamFinance", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.TeamStaff", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Spec.ExamPosition", "ExamPosition")
                        .WithMany("TeamStaffs")
                        .HasForeignKey("ExamPositionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.Spec.SpecStaff", "Staff")
                        .WithMany("TeamStaffs")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.Spec.ExaminationTeam", "Team")
                        .WithMany("TeamStaffs")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamPosition");

                    b.Navigation("Staff");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.User", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Spec.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.UserRole", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Spec.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.Spec.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.Contract", b =>
                {
                    b.Navigation("ExaminationTeams");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.ExamPosition", b =>
                {
                    b.Navigation("PatientExamRecords");

                    b.Navigation("TeamStaffs");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.ExaminationTeam", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("ExamPositions");

                    b.Navigation("InventoryIssues");

                    b.Navigation("OtherExpenses");

                    b.Navigation("Patients");

                    b.Navigation("QRSessions");

                    b.Navigation("TeamFinance");

                    b.Navigation("TeamStaffs");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.InventoryItem", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.SpecPatient", b =>
                {
                    b.Navigation("ExamRecords");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.SpecPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.SpecStaff", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("TeamStaffs");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Spec.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
