// <auto-generated />
// Manual migration: AddBatchMedicalRecord
// All Up() operations are additive-only (CREATE TABLE IF NOT EXISTS).
// Uses raw SQL (migrationBuilder.Sql) — model snapshot not updated here.

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using QuanLyDoanKham.API.Data;

#nullable disable

namespace QuanLyDoanKham.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260507000000_AddBatchMedicalRecord")]
    partial class AddBatchMedicalRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally minimal — raw SQL migration.
        }
    }
}
