// <auto-generated />
// This file is auto-generated by EF Core tooling.
// Manual migration: AddMedicalBatchDomain
// All Up() operations are additive-only (CREATE TABLE IF NOT EXISTS, ADD COLUMN IF NOT EXISTS).
// The model snapshot is NOT updated here because this migration uses raw SQL (migrationBuilder.Sql)
// and does not use EF Core's CreateTable/AddColumn fluent API.
// The snapshot will be updated when dotnet ef migrations add is run with the dev server stopped.

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using QuanLyDoanKham.API.Data;

#nullable disable

namespace QuanLyDoanKham.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506000000_AddMedicalBatchDomain")]
    partial class AddMedicalBatchDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // NOTE: This Designer file intentionally omits the full model snapshot
            // because this migration uses raw SQL statements (migrationBuilder.Sql)
            // rather than EF Core's fluent CreateTable API.
            //
            // The ApplicationDbContextModelSnapshot.cs will be regenerated correctly
            // when the dev server is stopped and `dotnet ef migrations add` is run
            // against the updated DbContext.
            //
            // This does NOT affect migration execution — Up() and Down() run correctly.
        }
    }
}
