// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyDoanKham.API.Data;

#nullable disable

namespace QuanLyDoanKham.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260407082744_LeanMedicalOps_v1")]
    partial class LeanMedicalOps_v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyDoanKham.API.Models.AppRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Quản trị hệ thống",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Quản lý nhân sự",
                            RoleName = "PersonnelManager"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "Quản lý hợp đồng",
                            RoleName = "ContractManager"
                        },
                        new
                        {
                            RoleId = 4,
                            Description = "Quản lý tính lương",
                            RoleName = "PayrollManager"
                        },
                        new
                        {
                            RoleId = 5,
                            Description = "Quản lý đoàn khám",
                            RoleName = "MedicalGroupManager"
                        },
                        new
                        {
                            RoleId = 6,
                            Description = "Quản lý kho vật tư",
                            RoleName = "WarehouseManager"
                        },
                        new
                        {
                            RoleId = 7,
                            Description = "Trưởng đoàn khám",
                            RoleName = "GroupLeader"
                        },
                        new
                        {
                            RoleId = 8,
                            Description = "Nhân viên đi đoàn",
                            RoleName = "MedicalStaff"
                        },
                        new
                        {
                            RoleId = 9,
                            Description = "Kế toán",
                            RoleName = "Accountant"
                        },
                        new
                        {
                            RoleId = 10,
                            Description = "Đại diện doanh nghiệp đối tác",
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.HasIndex("StaffId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$azxY7U9nnOEV4xF4Cto.gOLsbvUKtALtNoqMjMFRhVfP/45V1BrJ.",
                            RoleId = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.ApprovalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalStepId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApproverId")
                        .HasColumnType("int");

                    b.Property<string>("Decision")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("HealthContractId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStepId");

                    b.HasIndex("ApproverId");

                    b.HasIndex("HealthContractId");

                    b.ToTable("ApprovalHistories");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.ApprovalStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HealthContractId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("RequiredPermission")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HealthContractId");

                    b.HasIndex("RoleId");

                    b.ToTable("ApprovalSteps");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CompanySize")
                        .HasColumnType("int");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.ContractApprovalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("HealthContractId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StepName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("HealthContractId");

                    b.ToTable("ContractApprovalHistories");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.ContractApprovalStep", b =>
                {
                    b.Property<int>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StepId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RequiredPermission")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("StepId");

                    b.ToTable("ContractApprovalSteps");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.ContractAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HealthContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("HealthContractId");

                    b.ToTable("ContractAttachments");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.ContractFinancialSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HealthContractId")
                        .HasColumnType("int");

                    b.Property<decimal>("OtherCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("SnapshotAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StaffCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SupplyCost")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("HealthContractId");

                    b.ToTable("ContractFinancialSummaries");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.ContractRevenueSummary", b =>
                {
                    b.Property<int>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SummaryId"));

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HealthContractId")
                        .HasColumnType("int");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalContractValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalGroupCosts")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TotalGroups")
                        .HasColumnType("int");

                    b.HasKey("SummaryId");

                    b.HasIndex("HealthContractId");

                    b.ToTable("ContractRevenueSummaries");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.ContractStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HealthContractId")
                        .HasColumnType("int");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HealthContractId");

                    b.ToTable("ContractStatusHistories");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.GroupCost", b =>
                {
                    b.Property<int>("CostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CostId"));

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CalculatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OtherCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("StaffCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SupplyCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CostId");

                    b.HasIndex("CalculatedByUserId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupCosts");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.GroupPositionQuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Assigned")
                        .HasColumnType("int");

                    b.Property<int>("MedicalGroupId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("Required")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicalGroupId");

                    b.HasIndex("PositionId");

                    b.ToTable("GroupPositionQuotas");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.GroupStaffDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("CalculatedSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("GroupPositionQuotaId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.Property<double>("ShiftType")
                        .HasColumnType("float");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("WorkPosition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WorkStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("GroupPositionQuotaId");

                    b.HasIndex("PositionId");

                    b.HasIndex("StaffId");

                    b.ToTable("GroupStaffDetails");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.HealthContract", b =>
                {
                    b.Property<int>("HealthContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthContractId"));

                    b.Property<decimal>("AdvancePayment")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ContractCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContractName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentApprovalStep")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FinalSettlementValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SignerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SigningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UnitName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("HealthContractId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SignerId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.MedicalGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GroupLeaderStaffId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("HealthContractId")
                        .HasColumnType("int");

                    b.Property<string>("ImportFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Slot")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TeamCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GroupId");

                    b.HasIndex("GroupLeaderStaffId");

                    b.HasIndex("HealthContractId");

                    b.HasIndex("ManagerUserId");

                    b.ToTable("MedicalGroups");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.MedicalGroupPosition", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<int>("AssignedCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("PositionId");

                    b.HasIndex("GroupId");

                    b.ToTable("MedicalGroupPositions");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.PasswordResetRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<string>("NewPassword")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetRequests");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Module")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermissionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionKey")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            Module = "HopDong",
                            PermissionKey = "HopDong.View",
                            PermissionName = "Xem hợp đồng"
                        },
                        new
                        {
                            PermissionId = 2,
                            Module = "HopDong",
                            PermissionKey = "HopDong.Create",
                            PermissionName = "Tạo hợp đồng"
                        },
                        new
                        {
                            PermissionId = 3,
                            Module = "HopDong",
                            PermissionKey = "HopDong.Edit",
                            PermissionName = "Sửa hợp đồng"
                        },
                        new
                        {
                            PermissionId = 4,
                            Module = "HopDong",
                            PermissionKey = "HopDong.Approve",
                            PermissionName = "Phê duyệt hợp đồng"
                        },
                        new
                        {
                            PermissionId = 5,
                            Module = "HopDong",
                            PermissionKey = "HopDong.Reject",
                            PermissionName = "Từ chối hợp đồng"
                        },
                        new
                        {
                            PermissionId = 6,
                            Module = "HopDong",
                            PermissionKey = "HopDong.Upload",
                            PermissionName = "Đính kèm file hợp đồng"
                        },
                        new
                        {
                            PermissionId = 10,
                            Module = "DoanKham",
                            PermissionKey = "DoanKham.View",
                            PermissionName = "Xem đoàn khám"
                        },
                        new
                        {
                            PermissionId = 11,
                            Module = "DoanKham",
                            PermissionKey = "DoanKham.Create",
                            PermissionName = "Tạo đoàn khám"
                        },
                        new
                        {
                            PermissionId = 12,
                            Module = "DoanKham",
                            PermissionKey = "DoanKham.Edit",
                            PermissionName = "Sửa đoàn khám"
                        },
                        new
                        {
                            PermissionId = 13,
                            Module = "DoanKham",
                            PermissionKey = "DoanKham.SetPosition",
                            PermissionName = "Thiết lập vị trí đoàn"
                        },
                        new
                        {
                            PermissionId = 14,
                            Module = "DoanKham",
                            PermissionKey = "DoanKham.AssignStaff",
                            PermissionName = "Phân công nhân sự đoàn"
                        },
                        new
                        {
                            PermissionId = 15,
                            Module = "DoanKham",
                            PermissionKey = "DoanKham.ManageOwn",
                            PermissionName = "Quản lý đoàn mình phụ trách"
                        },
                        new
                        {
                            PermissionId = 20,
                            Module = "LichKham",
                            PermissionKey = "LichKham.ViewOwn",
                            PermissionName = "Xem lịch của mình"
                        },
                        new
                        {
                            PermissionId = 21,
                            Module = "LichKham",
                            PermissionKey = "LichKham.ViewAll",
                            PermissionName = "Xem toàn bộ lịch khám"
                        },
                        new
                        {
                            PermissionId = 30,
                            Module = "ChamCong",
                            PermissionKey = "ChamCong.QR",
                            PermissionName = "Mở QR chấm công"
                        },
                        new
                        {
                            PermissionId = 31,
                            Module = "ChamCong",
                            PermissionKey = "ChamCong.CheckInOut",
                            PermissionName = "Check-in/out nhân viên"
                        },
                        new
                        {
                            PermissionId = 32,
                            Module = "ChamCong",
                            PermissionKey = "ChamCong.ViewAll",
                            PermissionName = "Xem toàn bộ chấm công"
                        });
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SpecialtyRequired")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PositionId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            PermissionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            PermissionId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            PermissionId = 20,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            PermissionId = 21,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            PermissionId = 30,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            PermissionId = 31,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            PermissionId = 32,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 100,
                            PermissionId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 101,
                            PermissionId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 102,
                            PermissionId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 103,
                            PermissionId = 4,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 104,
                            PermissionId = 5,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 105,
                            PermissionId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 200,
                            PermissionId = 10,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 201,
                            PermissionId = 11,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 202,
                            PermissionId = 12,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 203,
                            PermissionId = 13,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 204,
                            PermissionId = 14,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 205,
                            PermissionId = 15,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 206,
                            PermissionId = 21,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 300,
                            PermissionId = 14,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 301,
                            PermissionId = 21,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 302,
                            PermissionId = 32,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.ScheduleCalendar", b =>
                {
                    b.Property<int>("CalendarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalendarId"));

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("CalendarId");

                    b.HasIndex("GroupId");

                    b.HasIndex("StaffId");

                    b.ToTable("ScheduleCalendars");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccountName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("CertificateNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmployeeType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullNameUnsigned")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IDCardBackPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDCardFrontPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDCardNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PracticeCertificatePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalaryType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StaffType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StandardWorkDays")
                        .HasColumnType("int");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StaffId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.AppUser", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyDoanKham.API.Models.AppRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId");

                    b.Navigation("Company");

                    b.Navigation("Role");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.ApprovalHistory", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.ApprovalStep", "ApprovalStep")
                        .WithMany()
                        .HasForeignKey("ApprovalStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.AppUser", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.HealthContract", "HealthContract")
                        .WithMany()
                        .HasForeignKey("HealthContractId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovalStep");

                    b.Navigation("Approver");

                    b.Navigation("HealthContract");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.ApprovalStep", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.HealthContract", "HealthContract")
                        .WithMany()
                        .HasForeignKey("HealthContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.AppRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HealthContract");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.AuditLog", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.ContractApprovalHistory", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.AppUser", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.HealthContract", "HealthContract")
                        .WithMany("ApprovalHistories")
                        .HasForeignKey("HealthContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("HealthContract");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.ContractAttachment", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.HealthContract", "HealthContract")
                        .WithMany("Attachments")
                        .HasForeignKey("HealthContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthContract");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.ContractFinancialSummary", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.HealthContract", "HealthContract")
                        .WithMany()
                        .HasForeignKey("HealthContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthContract");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.ContractRevenueSummary", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.HealthContract", "HealthContract")
                        .WithMany()
                        .HasForeignKey("HealthContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthContract");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.ContractStatusHistory", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.HealthContract", "HealthContract")
                        .WithMany("StatusHistories")
                        .HasForeignKey("HealthContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthContract");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.GroupCost", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.AppUser", "CalculatedByUser")
                        .WithMany()
                        .HasForeignKey("CalculatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyDoanKham.API.Models.MedicalGroup", "MedicalGroup")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalculatedByUser");

                    b.Navigation("MedicalGroup");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.GroupPositionQuota", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.MedicalGroup", "MedicalGroup")
                        .WithMany()
                        .HasForeignKey("MedicalGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalGroup");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.GroupStaffDetail", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.MedicalGroup", "MedicalGroup")
                        .WithMany("StaffDetails")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.GroupPositionQuota", "GroupPositionQuota")
                        .WithMany()
                        .HasForeignKey("GroupPositionQuotaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyDoanKham.API.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuanLyDoanKham.API.Models.Staff", "Staff")
                        .WithMany("GroupStaffDetails")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupPositionQuota");

                    b.Navigation("MedicalGroup");

                    b.Navigation("Position");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.HealthContract", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyDoanKham.API.Models.AppUser", "Signer")
                        .WithMany()
                        .HasForeignKey("SignerId");

                    b.HasOne("QuanLyDoanKham.API.Models.AppUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("Company");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Signer");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.MedicalGroup", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Staff", "GroupLeaderStaff")
                        .WithMany()
                        .HasForeignKey("GroupLeaderStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyDoanKham.API.Models.HealthContract", "HealthContract")
                        .WithMany("MedicalGroups")
                        .HasForeignKey("HealthContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.AppUser", "ManagerUser")
                        .WithMany()
                        .HasForeignKey("ManagerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GroupLeaderStaff");

                    b.Navigation("HealthContract");

                    b.Navigation("ManagerUser");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.MedicalGroupPosition", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.MedicalGroup", "MedicalGroup")
                        .WithMany("Positions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalGroup");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Notification", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.RolePermission", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.AppRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.ScheduleCalendar", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.MedicalGroup", "MedicalGroup")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDoanKham.API.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MedicalGroup");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.UserRole", b =>
                {
                    b.HasOne("QuanLyDoanKham.API.Models.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuanLyDoanKham.API.Models.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.AppRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.HealthContract", b =>
                {
                    b.Navigation("ApprovalHistories");

                    b.Navigation("Attachments");

                    b.Navigation("MedicalGroups");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.MedicalGroup", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("StaffDetails");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("QuanLyDoanKham.API.Models.Staff", b =>
                {
                    b.Navigation("GroupStaffDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
